tictactrip/luminator

__tests__/unit/index.ts
src/luminator.ts

Fix status of undefined when axios is throwing an non AxiosError

Fix status of undefined

---

__tests__/unit/index.ts
src/luminator.ts

- Resets the failCount and the failuresCountRequests and switchSessionId for the next request

FIX - Reset failuresCountRequests

---

__tests__/unit/index.ts
package.json
src/luminator.ts
yarn.lock

Check if the next request after an error passes

CHORE - Test created to simulate max failure req bug

---

package.json
tsconfig.json
yarn.lock

- packages updated 
- types exported

feat(typing): packages updated + types exported

---

__tests__/unit/index.ts
package.json
src/luminator.ts
tsconfig.json
tslint.json
yarn.lock

- Add axiosDefaultConfig property
- Update types and JSDoc
- Update tests
- Update Axios package

Feat: add axiosDefaultConfig property

---

package.json

fix: http proxy agent package

---

src/luminator.ts
yarn.lock

- yarn.lock with proxy agent package rollback
- refactor of getAxiosRequestConfig function

fix: update AxiosRequestConfig getter

---

src/index.ts
src/luminator.ts

- Create LuminatorResponse type
- Export types

feat: add custom response type

---

__tests__/unit/index.ts
src/index.ts
src/luminator.ts

Create a custom error class to handle Luminati related errors.

feat: create LuminatorError class

---

__tests__/unit/index.ts
src/luminator.ts

This PR aims to use random country.

feat: use random country

---

package.json
src/luminator.ts
yarn.lock

This PR aims to:
- not check HTTPS certificates.
- update some packages.

feat: don't check certificates

---

.eslintrc.js
.github/workflows/release.yml
.github/workflows/test.yml
README.md
package.json
yarn.lock

This PR aims to:
- include a CI/CD
- update packages

feat(global): packages updated + CI/CD integrated

---

package.json
yarn.lock

This PR aims to update all packages.

feat(package.json): packages updated

---

README.md

feat(README.md): documentation updated

---

src/classes/providers/proxyrack/index.ts

This PR aims to fix random Proxyrack getting random port function.

fix(proxyrack): ports index fixed

---

src/classes/providers/proxyrack/types.ts

This PR aims to export missing types.

feat(proxyrack): types exported

---

src/classes/providers/luminati/types.ts

This PR aims to export `ILuminatiProviderConfig` type.

feat(luminati): exports updated

---

.github/workflows/test.yml

chore: node version updated

---

__tests__/unit/__snapshots__/shifter.ts.snap
__tests__/unit/bright-data.ts
__tests__/unit/shifter.ts
package.json
src/classes/providers/base/types.ts
src/classes/providers/bright-data/index.ts
src/classes/providers/proxyrack/index.ts
src/classes/providers/shifter/index.ts
tsconfig.json
yarn.lock

+ http + https agent updated
+ don't verify certs
+ don't check external libs definitions

feat: agents updated

---

__tests__/unit/shifter.ts
src/classes/providers/shifter/index.ts

+ shifter uses HTTP instead of HTTPS

fix: shifter use http
